language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_ece416526abb_key -iv $encrypted_ece416526abb_iv
    -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - git remote set-url origin git@github.com:CCoffie/CalebCoffie.com.git
